In [2]:
import numpy as np

# Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [4]:
a=np.arange(2,50,3)
print(a)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [8]:
#creating a list x of 5 elements
x=[1,2,3,4,5]
print(type(x))

<class 'list'>


In [9]:
#creating a list y of 5 elements
y=[6,7,8,9,1]
print(type(y))

<class 'list'>


In [14]:
#converting the list to numpy array
s=np.array(x)
print(type(s))

t=np.array(y)
print(type(t))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [18]:
#concatenate the numpy array s and t
concat=np.concatenate((s,t))
print(concat)

[1 2 3 4 5 6 7 8 9 1]


In [19]:
sorted_array=np.sort(concat)
print(sorted_array)

[1 1 2 3 4 5 6 7 8 9]


# Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.
 

In [22]:
a=[[1,2,3,4],
  [5,6,7,8]]
print(np.ndim(a))  #dimension
print(np.size(a))  #size

2
8


# Questions 4:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [36]:
n1=np.array([1,2,3])
print(n1)
print(type(n1))
print(np.shape(n1))

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [35]:
n1_dim=np.expand_dims(n1,axis=1)
print(n1_dim)
print(np.shape(n1_dim))

[[1]
 [2]
 [3]]
(3, 1)


In [42]:
#using reshape
n2=np.arange(12).reshape(4,3)
print(n2)
print(n2.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)


In [46]:
n3=n2.reshape(6,2)  #syntax: reshape(row,column)
print(n3.shape)

(6, 2)


# Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [51]:
square_1=np.arange(4).reshape(2,2)
print(square_1)

square_2=np.arange(4).reshape(2,2)
print(square_2)

[[0 1]
 [2 3]]
[[0 1]
 [2 3]]


In [52]:
#stack horizontally
np.hstack((square_1,square_2))

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

In [53]:
#stack vertically
np.vstack((square_1,square_2))

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3]])

# Questions 6:
How to get unique items and counts of unique items?

In [62]:
a=np.array([2,1,3,2,1])
#unique items
print(np.unique(a))

#count of unique items
print(np.unique(a).size)


[1 2 3]
3
